apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: corona-go
    version: {{ .Values.version | default "v1" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: corona-go
      version: {{ .Values.version | default "v1" }}
  template:
    metadata:
      labels:
        app: corona-go
        version: {{ .Values.version | default "v1" }}
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "8200,8201"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "corona-go"
        vault.hashicorp.com/agent-inject-secret-app-creds: "app-creds/data/corona-go"
        vault.hashicorp.com/agent-inject-template-app-creds: |
          {{`{{- with secret "app-creds/data/corona-go" -}}
          apiKey={{ .Data.data.apiKey }}
          externalServiceToken={{ .Data.data.externalServiceToken }}
          {{- end }}`}}
        vault.hashicorp.com/agent-requests-cpu: "20m"
        vault.hashicorp.com/agent-requests-mem: "32Mi"
        vault.hashicorp.com/agent-limits-cpu: "50m"
        vault.hashicorp.com/agent-limits-mem: "64Mi"
    spec:
      serviceAccountName: corona-go
      nodeSelector:
        kubernetes.io/hostname: k8s-worker
      hostAliases:
        - ip: "10.146.183.231"
          hostnames:
            - "vault.lab"
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: APP_VERSION
              value: "{{ .Values.image.tag }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 15
