image:
  repository: harbor.lab:8080/library/corona-go
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 8080

service:
  type: NodePort
  port: 8080
  nodePort: 30082

imagePullSecret: harbor-cred

hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 70

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"
nodeSelector:
  kubernetes.io/hostname: k8s-worker

version: v1  
